<?php
/**
 *                                                 )
 *                                               (  (
 *                                              ) ) )
 *                  ......,.....................)  )
 *                 |.....|..................... ))
 *                                 [[[_________________________________]]]
 *                                         Blog: www.qingchen.red
 *                                          Created by PhpStorm.
 *                                            Date: 2017/6/11
 *                                             Time: 16:15
 *                                              User: 清晨
 *
 */

namespace app\admin\controller;


use app\admin\model\auth;
use app\admin\model\role_auth;
use app\admin\model\user_role;
use think\Controller;
use think\Request;

class Base extends Controller
{
    protected $user_id;
    protected $user_name;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session('user_id') == null) {
            $this->user_id = session('user_id');
            $this->user_name = session('user_name');
            if (!$this->_checkAuthor($this->user_id)) {
                $this->error('你没有权限操作！','admin/Index/index');
            }
        }
    }

    public function _checkAuthor($user_id)
    {
        if (!$user_id==1) {
            $request = Request::instance();
            $c = $request->controller();
            $a = $request->action();
            $user_role = user_role::get(['user_id' => $user_id]);
            if (isset($user_role)) {
                $list = role_auth::all(['role_id' => $user_role['role_id']]);
                if (isset($list)) {
                    foreach ($list as $k) {
                        $auth = auth::get($k->auth_id);
                        if ($auth->c == $c && $auth->a == $a) {
                            return true;
                        }
                    }
                }
            }
        }else{
            return true;
        }
        return false;
    }

}